### PR TITLE
Controlpanel

### LINKED ISSUE #291: display units in slider widgets
Low-priority feature request: it would be nice if slider widgets displayed units, either on the left hand side with the variable name/key, or on the right hand side with the value.

Unfortunately both appear a bit non-straightforward to implement; discussion welcome on ideas for doing this cleanly.

### PR DESCRIPTION
**Pull request by whoburg**
This is a cleaned up version of #452 that includes only the relevant commits not already on master. Closes #291

### CODE REVIEW

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
todo: 
* [ ] move controlpanel and interact to .interactive
* [ ] add ractor controlpanel
* [ ] don't print that HTML out unless in an IPython notebook? or just give it a __repr__ of None (hack)

**Comment by whoburg** [comment]
reviewed; see inlines. only failing Jenkins on elcap.

**Comment by galbramc** [comment]
retest this please

**Comment by bqpd** [comment]
@whoburg, I think this is ready to merge (addressed your code review)

**Comment by whoburg** [comment]
This looks great. I'm going to merge. A couple comments to please address post-merge:

 - what's happening with the unchecked "add ractor controlpanel" item?
 - I pushed a minor change; please double-check you're ok with it.

**Comment by whoburg** [comment]
I just tried to create a control panel in an ipython notebook, and I get the error below. Is this expected?

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-9fb0dde5e327> in <module>()
      3 import gpkit
      4 br = BreguetRange()
----> 5 br.controlpanel()

/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/model.pyc in controlpanel(self, *args, **kwargs)
    701         live. args and kwargs are passed on to interact()
    702         """
--> 703         from .interactive.widgets import modelcontrolpanel
    704         return modelcontrolpanel(self, *args, **kwargs)
    705 

/Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkit/interactive/widgets.py in <module>()
----> 1 import ipywidgets as widgets
      2 from traitlets import link
      3 from ..small_scripts import is_sweepvar
      4 from ..small_classes import Numbers
      5 

ImportError: No module named ipywidgets
```

**Comment by bqpd** [comment]
Have you installed the ipywidgets package? It's no longer bundled with IPython

**Comment by bqpd** [comment]
re: ractor controlpanel, unchecked because that's part of the larger "move ractor stuff into cadtoons"

**Comment by whoburg** [comment]
Sweet, installing ipywidgets worked. Do we need to mention the installation of ipywidgets in our install instructions docs?

**Comment by bqpd** [comment]
I think we should mention it in the controlpanel / intreact docs?

**Comment by bqpd** [comment]
Maybe in both, actually.

**Comment by whoburg** [comment]
yeah, in the controlpanel / interact docs sounds good, but those are such cool features that I would really hate for a user to say "oh, this requires some weird add-on package; I'm not going to use it". Might be better to just encourage getting it installed right away, under the assumption that many gpkit users will want the interactive features.

**Comment by whoburg** [comment]
should I open an issue on documenting that, or are you on it?

**Comment by bqpd** [comment]
on it :p

**Pull request merged**
