### PR TITLE
issue476/477 debugging

### PR DESCRIPTION
**Pull request by whoburg**
Debug issue 476 and 477 via Jenkins. Not intended to be merged.

### CODE REVIEW

**Comment by bqpd** [comment]
Fails only on cvxopt? Hmmm...

**Comment by bqpd** [comment]
Confirmed on my computer.

**Comment by bqpd** [comment]
@cjk12, you might want to update your MOSEK license, it looks like CVXopt could be the issue.

**Comment by whoburg** [comment]
ready to close this with the conclusion that the example is a GP solver error for cvxopt?

**Comment by bqpd** [comment]
I am!

**Comment by whoburg** [comment]
closing; @cjk12 let us know if you disagree

**Pull request closed without merging**
