### PR TITLE
Auto examples

### LINKED ISSUE #232: Read The Docs Examples should be Unit Tests
At some point, everything we have online should be included in the unit tests.  Stems from issue #231

### PR DESCRIPTION
**Pull request by bqpd**
Closes #232

### CODE REVIEW

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
@whoburg, this is ready for review.

**Comment by bqpd** [comment]
I'm going to merge this so I can release 0.3.2 to pip, but please review and leave comments! We'll cover them in 0.4.0

Also @pgkirsch, you might have opinions on this...

**Comment by whoburg** [comment]
This looks great.

It would be nice to have a short "how to make a new example" somewhere in the documentation. It would describe how to add the example to `t_examples`, along with any other steps needed.

**Pull request merged**
