### PR TITLE
refactor signomial loop conditional

### PR DESCRIPTION
**Pull request by bqpd**
also add #348 proto-test

### CODE REVIEW

**Comment by bqpd** [comment]
ready4review

**Comment by whoburg** [comment]
Looks good to me, @pgkirsch if you agree you can hit merge.

**Comment by pgkirsch** [comment]
Sorry for the delay

**Comment by whoburg** [comment]
`495 additions and 513 deletions`

that's progress!

**Comment by bqpd** [comment]
Check the release notes :D

**Pull request merged**
