### PR TITLE
build as function, not on import. closes #310

### LINKED ISSUE #310: eliminate side effects from gpkit.build import
As described in https://github.com/convexopt/gpkit/commit/6623431be55c03a738941e2b834cc5908e4d4b99#commitcomment-12502281

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
Working on Jenkins, ready for code review.

**Comment by bqpd** [comment]
Working on Jenkins, ready for code review.

**Comment by galbramc** [comment]
I'm going to use this pull request to test a couple of thins with jenkins

**Comment by galbramc** [comment]
test this please

**Comment by bqpd** [comment]
Nice! Would we be told which tests failed if any had?

**Comment by galbramc** [comment]
I'm not sure. You can create a dummy pull request like @whoburg did before with and intentional error somewhere in the testing and we can see what happens. It would give me a pull request that I can use just to tweak these settings as well.

**Comment by bqpd** [comment]
Created as #324

**Comment by whoburg** [comment]
looks good, merging

**Pull request merged**
