### PR TITLE
Core refactor

### PR DESCRIPTION
**Pull request by whoburg**
Ongoing improvements to core (low-level) classes and functions.

Changes:
 - [x] Simplify `VarKey` constructor and attributes
 - [x] `small_classes.Numbers` now include `Quantity` (instead of appending `Quantity` in each .py file).
 - [x] refactor `HashVector` and add tests

### CODE REVIEW

**Comment by bqpd** [comment]
Oops, looks like there's another merge conflict...

**Comment by whoburg** [comment]
I can look at that...

**Comment by bqpd** [comment]
Different units checking in nomials.py

**Comment by whoburg** [comment]
Fixed -- should be ready to merge

**Comment by bqpd** [comment]
(...is "no test results" good test results?)

**Comment by whoburg** [comment]
That's a confusing comment from @acdl-jenkins, especially since I have an e-mail from Jenkins at 10:33am today, about this PR, showing 198 tests passed and 0 failures/errors...

@galbramc

**Comment by galbramc** [comment]
I am equally puzzled about "Build finished. No test results found.", and we are not the only ones: http://stackoverflow.com/questions/31013331/jenkins-github-pull-request-builder-status-message

I'm still hunting down why you got that message. I'm not even sure why all of a sudden messages started appearing. I did update jenkins this morning and that might be the reason why you get the commits.

**Comment by galbramc** [comment]
@whoburg I made some changes to jenkins. Could you trigger a build with the comment "retest this please"?

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
Jenkins now happy thanks to @galbramc  -- @bqpd this is ready to merge if you agree.

**Comment by whoburg** [comment]
Should I hold off on merging this?

**Comment by bqpd** [comment]
+1

**Comment by bqpd** [comment]
retest this please

**Pull request merged**
