### PR TITLE
Build script improvements

### PR DESCRIPTION
**Pull request by bqpd**
The build script may well be worth a full refactoring at some point, but for now this deals with issues discovered by @galbramc (and incorporates his fixes and suggestions).

Confirmed on my linux computer, will test on my windows computer.
Please test on Macs!

### CODE REVIEW

**Comment by galbramc** [comment]
@whoburg Could you merge this asap. All other testing on reynolds will fail until this is merged.

**Comment by whoburg** [comment]
Testing now on my mac

**Comment by whoburg** [comment]
Install script appeared to run successfully, but there's a `mosek_bin_dir` issue:

```python
======================================================================
ERROR: test_simpleflight (t_geometric_program.t_GP_mosek_cli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 76, in test_simpleflight
    self.simpleflight_test_core(sf.gp())
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 43, in simpleflight_test_core
    sol = gp.solve(printing=False)
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 353, in _solve
    solverfn = cli_expopt.imize_fn(filename)
  File "gpkit/_mosek/cli_expopt.py", line 18, in imize_fn
    os.environ['PATH'] = os.environ['PATH']+':%s' % settings["mosek_bin_dir"][0]
KeyError: 'mosek_bin_dir'

======================================================================
ERROR: test_trivial_gp (t_geometric_program.t_GP_mosek_cli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 21, in test_trivial_gp
    sol = prob.solve(printing=False)["variables"]
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 353, in _solve
    solverfn = cli_expopt.imize_fn(filename)
  File "gpkit/_mosek/cli_expopt.py", line 18, in imize_fn
    os.environ['PATH'] = os.environ['PATH']+':%s' % settings["mosek_bin_dir"][0]
KeyError: 'mosek_bin_dir'

======================================================================
ERROR: test_trivial_vector_gp (t_geometric_program.t_GP_mosek_cli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 34, in test_trivial_vector_gp
    sol = prob.solve(printing=False)['variables']
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 353, in _solve
    solverfn = cli_expopt.imize_fn(filename)
  File "gpkit/_mosek/cli_expopt.py", line 18, in imize_fn
    os.environ['PATH'] = os.environ['PATH']+':%s' % settings["mosek_bin_dir"][0]
KeyError: 'mosek_bin_dir'

======================================================================
ERROR: test_zeroing (t_geometric_program.t_GP_mosek_cli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 105, in test_zeroing
    sol = GP(1/L, [L-5*k <= 10]).solve(printing=False, solver=self.solver)
  File "gpkit/geometric_program.py", line 330, in solve
    return self._solve(*args, **kwargs)
  File "gpkit/geometric_program.py", line 353, in _solve
    solverfn = cli_expopt.imize_fn(filename)
  File "gpkit/_mosek/cli_expopt.py", line 18, in imize_fn
    os.environ['PATH'] = os.environ['PATH']+':%s' % settings["mosek_bin_dir"][0]
KeyError: 'mosek_bin_dir'

======================================================================
ERROR: test_trivial_sp (t_geometric_program.t_SP_mosek_cli)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/tests/t_geometric_program.py", line 129, in test_trivial_sp
    sol = sp.localsolve(printing=False, solver=self.solver)
  File "gpkit/signomial_program.py", line 149, in localsolve
    sol = self._solve(printing=printing, *args, **kwargs)
  File "gpkit/geometric_program.py", line 353, in _solve
    solverfn = cli_expopt.imize_fn(filename)
  File "gpkit/_mosek/cli_expopt.py", line 18, in imize_fn
    os.environ['PATH'] = os.environ['PATH']+':%s' % settings["mosek_bin_dir"][0]
KeyError: 'mosek_bin_dir'

----------------------------------------------------------------------
Ran 59 tests in 0.918s

FAILED (errors=5)
```

**Comment by whoburg** [comment]
wait, this might be my fault for forgetting to install ctypesgen. standby.

**Comment by bqpd** [comment]
You should be able to use mosek_cli without ctypesgen. Pushing a small fix.

**Comment by whoburg** [comment]
Ok, on my mac I confirmed that small update makes the tests run (via mosek_cli) even without ctypesgen installed, and that with ctypesgen installed, the gpkit build works and all tests pass.

**Comment by bqpd** [comment]
You didn't get the Jenkins issues? Check if there's a line in your bashrc
that's adding to the DYLD library path; with that commented out do the
tests still work?

**Comment by whoburg** [comment]
Hmm, there are many such lines in my bashrc. After deleting the extra ones and commenting the last, the tests indeed fail. 

Was I too quick on the draw with merging?

**Comment by bqpd** [comment]
Well, merging fixed the linux issues.

**Comment by bqpd** [comment]
New PR: https://github.com/convexopt/gpkit/pull/199

**Pull request merged**
