### PR TITLE
simple_wing example touch-up

### PR DESCRIPTION
**Pull request by whoburg**
* Corrected `Variable` keyword argument from `descr` to `label`
* Added units
* pep8
* added simple_wing to Makefile and remade output
* Added vars for wing weight model params

### CODE REVIEW

**Comment by bqpd** [comment]
This looks nice. We should standardize on the `label=` tags; some variable declarations use them, but some don't. I'm not sure which is better.

**Comment by whoburg** [comment]
Related: I was thinking of opening a ticket to eliminate the `**kwargs` from `Variable`'s `__init__`. Proposal would be to explicitly enumerate kwargs we allow, and disallow all others. Reasoning is that the `descr=` mistake this PR replaced went through without error; I think that's potentially confusing for users.

Anyone have thoughts? if so let's open that discussion in a new ticket.

**Comment by bqpd** [comment]
I like the notion that users (and libraries) can use custom keys for their own purposes; we've used this to test things like an sp_init flag.

**Comment by whoburg** [comment]
Ok, fair enough... in that case perhaps my point can be addressed by tidying up / improving the docstring.

**Pull request merged**
