### PR TITLE
No signomial objectives

### PR DESCRIPTION
**Pull request by bqpd**
I'm not comfortable creating a dummy variable to hold the constraint for the user, so I added a hopefully-helpful error message.

### CODE REVIEW

**Comment by pgkirsch** [comment]
It looks like I duplicated some of these changes in #337 sorry. I'm fine with this replacing mine.

**Comment by whoburg** [comment]
Just grabbed the commit message from 1b19835b986dc82161e8ba396e1c2ed8fbbdc4a7. This fixes other things like the comma vs period -- are those fixes replicated elsewhere?

**Comment by bqpd** [comment]
Augh, which error message are we using?

**Comment by bqpd** [comment]
Since this is open again, I'll edit the while loop conditional in this branch.

**Comment by whoburg** [comment]
I vote for the one already on master, though making it a `TypeError` not `ValueError`. Those changes are already pushed to this PR in 01870c25d3df5bdd0fbbd20609c281135de77ed9.

**Comment by bqpd** [comment]
Okay. What about the one I just pushed?

**Comment by bqpd** [comment]
retest this please

**Comment by pgkirsch** [comment]
I'm fine with using @bqpd's error message because it is slightly more specific.

**Comment by bqpd** [comment]
Actually, I'll add the new condition in #343

**Comment by bqpd** [comment]
retest this please

**Comment by whoburg** [comment]
which takes priority, this or #347 ?

**Comment by bqpd** [comment]
Merge whichever, I'll fix the other.

**Comment by bqpd** [comment]
Actually wait. Let's close this one and just merge that one.

**Comment by whoburg** [comment]
I merged that one, as instructed  :/

**Comment by bqpd** [comment]
Yeah,this was totally my mistake :p

**Pull request closed without merging**
