### PR TITLE
model composition

### PR DESCRIPTION
**Pull request by bqpd**
This first draft seems to work, except for using '&' with vectors.

There's two tests which need to be added: one testing everything with vectors, and one testing `Model.varsbyname`

Also needs a few docstrings, documentation, etc.

### CODE REVIEW

**Comment by bqpd** [comment]
@whoburg ready for initial review

**Comment by whoburg** [comment]
ok, reviewing now.

**Comment by whoburg** [comment]
initial code review complete, haven't looked at responses yet, but will.

**Comment by whoburg** [comment]
What's the status of this? I think I've nit-picked it enough - should we merge, or were there some tests that needed to be added first?

**Comment by bqpd** [comment]
I'd like to get vectors working first, I think...

**Comment by bqpd** [comment]
Merging by popular demand, will create issues for the unresolved features.

**Pull request merged**
