### PR TITLE
Pylint config

### PR DESCRIPTION
**Pull request by whoburg**
closes #213; allows us to continue editing config settings before merging.

### CODE REVIEW

**Comment by whoburg** [comment]
Let's post proposed config changes here. Anyone who doesn't like a proposed change, speak up.

**Comment by whoburg** [comment]
Proposed change 1: add 

`ignored-modules = numpy`

under `[typecheck]`. Justification: otherwise, we get `no-member` errors for accessing numpy member functions, such as `np.array`.

**Comment by whoburg** [comment]
Proposed change 2:

change `variable-rgx=[a-z_][a-z0-9_]{2,30}$`
to:        `variable-rgx=[a-z_][a-z0-9_]{0,30}$`

Justification: otherwise, get `invalid-name` errors for single-character variable names, like `x`.

**Comment by whoburg** [comment]
Proposed change 3:

change
`ignore=CVS`
to
`ignore=CVS,expopt_h.py`

Justification: expopt_h.py is auto generated by ctypesgen, and full of violations.

**Comment by bqpd** [comment]
Also `ctypesgen.py`, which is not our code.

**Comment by whoburg** [comment]
Yes -- remind me why we have a copy of that in our repo?

**Comment by bqpd** [comment]
We use it to compile the python bindings for mosek; the license for it is
contained in a comment.

**Comment by whoburg** [comment]
Pushed first three proposed changes to this pull request branch.

**Comment by bqpd** [comment]
Propose the following name allowances: 

```
# Regular expression which should only match correct function names
function-rgx=[a-z_][a-z0-9_]{1,30}$

# Regular expression which should only match correct method names
method-rgx=[a-z_][a-z0-9_]{1,30}$

# Regular expression which should only match correct instance attribute names
attr-rgx=[a-z_][a-z0-9_]{1,30}$

# Regular expression which should only match correct argument names
argument-rgx=[a-z_][a-zA-Z0-9_]{1,30}$

# Regular expression which should only match correct variable names
variable-rgx=[a-z_][a-zA-Z0-9_]{1,30}$
```

**Comment by bqpd** [comment]
`no-members` issues are showing up frequently in situations that are only problematic if you don't properly track the SP << GP inheritance (for example). Ignoring them seems extreme, however.

**Comment by whoburg** [comment]
slightly more restrictive counter-proposal to the name allowances above:

```
# Regular expression which should only match correct function names
function-rgx=[a-z_][a-z0-9_]{2,30}$

# Regular expression which should only match correct method names
method-rgx=[a-z_][a-z0-9_]{2,30}$

# Regular expression which should only match correct instance attribute names
attr-rgx=[a-z_][a-z0-9_]{2,30}|A|cs|c$

# Regular expression which should only match correct argument names
argument-rgx=[a-z_][a-z0-9_]{2,30}$

# Regular expression which should only match correct variable names
variable-rgx=[a-zA-Z_][a-zA-Z0-9_]{0,30}$
```

differences / discussion points:
* [ ] function names: do we have and/or need any 2-letter function names?

* [ ] method names: do we have and/or need any 2-letter method names?

* [ ] attribute names: I've proposed special-casing the short attributes we care about, because I think extremely short names are indeed confusing.
attr-rgx=[a-z_][a-z0-9_]{2,30}$

* [ ] argument names: I'm on the fence, but I'm tempted to not allow short ones. Are there specific examples where we really benefit from short or capitalized arguments? As one example, geometric_program has a lot of arguments called `p`, which I claim would be clearer to call `posy`.

* [x] variable names: agreed
variable-rgx=[a-z_][a-z0-9_]{0,30}$

**Comment by bqpd** [comment]
It's kind of nice for small functions to be able to have small arguments, but I see what you're saying wrt `p`/`posy`.

**Comment by whoburg** [comment]
Pushed agreed upon name allowances to this branch.

Re: small arguments for small functions -- I've specifically been confused by some of those, especially when undocumented, so I left it strict for now. But very open to changing if there is a specific example where short names are really nice.

**Comment by whoburg** [comment]
Another proposal:

add `disable=superfluous-parens` under [MESSAGES CONTROL]. Reason: otherwise `print('msg')`, written in python3-compatible format, generates a superfluous-parens warning/error.

**Comment by bqpd** [comment]
Oh, yes, then.

**Comment by bqpd** [comment]
What about pylint's problems with dynamically-created classes?

**Comment by whoburg** [comment]
I haven't fully grokked the dynamically-created class issues, but it seems related to the `numpy` no-member warnings.

Open to suggestions, just want to make sure we don't disable useful errors.

**Comment by whoburg** [comment]
Is this part of the config relevant/useful?

```
# List of members which are set dynamically and missed by pylint inference
# system, and so shouldn't trigger E0201 when accessed. Python regular
# expressions are accepted.
generated-members=REQUEST,acl_users,aq_parent
```

**Comment by bqpd** [comment]
Sticking `SP` in there doesn't make the `no-members` warnings go away for me.

**Comment by whoburg** [comment]
Shall we merge this, and continue iterating in follow-on issues?

**Comment by bqpd** [comment]
Hmm, sounds good to me! Unless this will cause jenkins builds to feel like they're failing?

**Comment by whoburg** [comment]
Why would merging this cause jenkins failures? Sorry if I'm being dumb.

**Comment by galbramc** [comment]
I don't know why it would cause a failure. Last time this was tested I don't think we had jenkins configured to ignore compiler errors. I believe you can you request jenkins to test this pull request by posting the comment "retest this please".

**Comment by whoburg** [comment]
retest this please

**Comment by galbramc** [comment]
The last two mssages were from me. Forgot that I had logged in as acdl-jenkins

**Comment by whoburg** [comment]
Re: Were the fixes for windows merged into master?:

Yes, @bqpd pushed fixes for windows directly to master in e747aacf3e0e3970e8bf35267a0ca17f70af897e and a88a8f47726886ca6451f02c36e1e832b2c5f415.

**Comment by whoburg** [comment]
retest this please

**Comment by galbramc** [comment]
Jenkins does not try to connect to github in the same way when I trigger the build manually. @whoburg could you post "retest this please" again?

**Comment by whoburg** [comment]
retest this please

**Comment by galbramc** [comment]
I just accepted. Ask for a test one more time.

**Comment by whoburg** [comment]
retest this please

**Pull request merged**
