### PR TITLE
rename ctypesgen.py to modified_ctypesgen.py

### PR DESCRIPTION
**Pull request by whoburg**
Rename ctypesgen.py to modified_ctypesgen.py, so it’s more transparent what happened (we added command line options to the script).

### CODE REVIEW

**Comment by whoburg** [comment]
@bqpd assigning you since this touches the build script. It seems to run fine for me still.

**Comment by bqpd** [comment]
I...think Jenkins built it ok? Hard to tell.

**Comment by whoburg** [comment]
Yes, as far as I can tell it seems to be building fine and passing all our unit tests; Jenkins seems to be marking as failure due to pylint... I think?

I also find it hard to read.

**Comment by galbramc** [comment]
Yes this passes the tests on Linux and Mac, still have the failures on Windozs due to deleting the non-empty directory,

**Comment by whoburg** [comment]
Ok, so given that the build failures on windows are not due to the changes under this pull request, I think we can merge. @bqpd, if you agree, please do so.

**Comment by bqpd** [comment]
SGTM

**Comment by whoburg** [comment]
Just spent 5 minutes trying to determine whether this means "sounds good to me" or "silently giggling to myself".

**Comment by bqpd** [comment]
Hehehe. The former.

**Pull request merged**
