### PR TITLE
added intentionally failing test

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by bqpd** [comment]
It would also be nice if acdl-jenkins deleted / edited its comments after testing...failing that, the middle comment isn't particularly useful.

**Comment by galbramc** [comment]
I don't think there is an option to delete comments. However, if you add acdl-jenkins as a collaborator I believe jenkins can instead chance the "status" of the pull request. I don't exactly know what that means, but it might be less intrusive than the comments.

**Comment by galbramc** [comment]
The middle comment is there because if the testing machines are full with jobs, your test can't build until there are available processors. Hence the "trigger", "build", "result" sequence of messages.

**Comment by galbramc** [comment]
@whoburg can we try adding acdl-jenkins as a collaborator again? I've fixed things now so that Bob does not get swamped with emails.

**Comment by whoburg** [comment]
added our continuous_integration team back as a collaborator -- it includes a acdl_jenkins and galbramc. @galbramc would you like to be removed from that team?

**Comment by galbramc** [comment]
You can remove @galbramc. No need for my account to have write access. But you need to give acdl-jenkins push permissions for it to change the status on pull requests.

**Comment by galbramc** [comment]
Well, I guess I can play with the acdl-jenkins permissions now that you added me?

**Comment by galbramc** [comment]
Looks like you already removed me.

**Comment by whoburg** [comment]
try again now on the acdl-jenkins write access

**Comment by galbramc** [comment]
test this please

**Comment by galbramc** [comment]
Looks like it's working.

**Comment by whoburg** [comment]
that was super cool.

**Comment by galbramc** [comment]
This is the behavior you should have on all pull requests now. 

Hang on to this pull request for a little bit and let me do some research on the "No test results found." message. I want to see if I can fix that.

**Comment by whoburg** [comment]
excellent

**Comment by galbramc** [comment]
Well... @bqpd @whoburg, it looks like it's somewhat hard coded. I'm guessing I would actually have to propose a fix to the plugin source. That's more work than I'm willing to do at the moment, so lets just cross our fingers someone else fixes this. I did see someone else raise the issue in the past 20 days. So for now, just ignore "No test results found", it's not true.

**Comment by galbramc** [comment]
I forgot to say that you can go ahead and delete this pull request. You should be good to go.

**Comment by bqpd** [comment]
The integration with github is amazing, thanks @galbramc!

**Comment by galbramc** [comment]
Yeah. I didn't know it would be this slick! There is one more thing I want
to do, but we should work on that after you have cut your release tomorrow.

**Pull request closed without merging**
