### PR TITLE
Small fixes for 0.3.4

### PR DESCRIPTION
**Pull request by bqpd**

### CODE REVIEW

**Comment by whoburg** [comment]
ready for review?

**Comment by bqpd** [comment]
Sure! doesn't close #469 yet, though

**Comment by whoburg** [comment]
reviewed

**Comment by bqpd** [comment]
Great! Added another commit, closing #441 and responding to comments.

**Comment by whoburg** [comment]
additional commits reviewed

**Comment by whoburg** [comment]
looks good -- ready to merge?

**Pull request merged**
