### PR TITLE
Small improvements

### LINKED ISSUE #379: Solver error for increased-resolution GP
EDIT: See below for MWE

Discovered using the beam example: if I discretize the beam with 100 points, it works, if I discretize with 1000 points, it doesn't.

Working code:
```
from gpkit.shortcuts import *
import numpy as np
N = 100
L = 5.
dx = L/(N-1)
ei = 1E4
EI = Var("EI", ei)
P = 100.
p = Vec(N, "p", descr="Distributed load")
p = p.sub(p, P*np.ones(N))
V  = Vec(N, "V", label="Internal shear")
M  = Vec(N, "M", label="Internal moment")
th = Vec(N, "th", label="Slope")
w  = Vec(N, "w", label="Displacement")
eps = 1E-16 #something small
substitutions = {var: eps for var in [V[-1], M[-1], th[0], w[0]]}
objective = w[-1]
constraints = [V.left[1:N]     >= V[1:N]    + 0.5*dx*(p.left[1:N]    + p[1:N]),
               M.left[1:N]     >= M[1:N]    + 0.5*dx*(V.left[1:N]    + V[1:N]),
               th.right[0:N-1] >= th[0:N-1] + 0.5*dx*(M.right[0:N-1] + M[0:N-1])/EI,
               w.right[0:N-1]  >= w[0:N-1]  + 0.5*dx*(th.right[0:N-1]+ th[0:N-1])
              ]
m = Model(objective, constraints, substitutions)
sol = m.solve(verbosity=1)
```

Output:
```

Cost
----
 0.7812

Free Variables
--------------
 M : [ 1.25e+03  1.22e+03  1.2e+03   1.18e+03 ... ] Internal moment
 V : [ 500       495       490       485      ... ] Internal shear 
th : [  -        0.00625   0.0124    0.0184   ... ] Slope          
 w : [  -        0.000158  0.000628  0.0014   ... ] Displacement   

Constants
---------
EI : 1e+04                                                         
 M : [  -         -         -         -       ... ] Internal moment
 V : [  -         -         -         -       ... ] Internal shear 
th : [ 1e-16      -         -         -       ... ] Slope          
 w : [ 1e-16      -         -         -       ... ] Displacement   

Sensitivities
-------------
EI : -1 
```

Failing code:
```
from gpkit.shortcuts import *
import numpy as np
N = 1000
L = 5.
dx = L/(N-1)
ei = 1E4
EI = Var("EI", ei)
P = 100.
p = Vec(N, "p", descr="Distributed load")
p = p.sub(p, P*np.ones(N))
V  = Vec(N, "V", label="Internal shear")
M  = Vec(N, "M", label="Internal moment")
th = Vec(N, "th", label="Slope")
w  = Vec(N, "w", label="Displacement")
eps = 1E-16 #something small
substitutions = {var: eps for var in [V[-1], M[-1], th[0], w[0]]}
objective = w[-1]
constraints = [V.left[1:N]     >= V[1:N]    + 0.5*dx*(p.left[1:N]    + p[1:N]),
               M.left[1:N]     >= M[1:N]    + 0.5*dx*(V.left[1:N]    + V[1:N]),
               th.right[0:N-1] >= th[0:N-1] + 0.5*dx*(M.right[0:N-1] + M[0:N-1])/EI,
               w.right[0:N-1]  >= w[0:N-1]  + 0.5*dx*(th.right[0:N-1]+ th[0:N-1])
              ]
m = Model(objective, constraints, substitutions)
sol = m.solve(verbosity=1)
```

Output
```
RuntimeWarning: final status of solver 'mosek' was 'UNKNOWN', not 'optimal'.

To generate a feasibility-finding relaxed version of your
Geometric Program, run model.program.feasibility_search().

The infeasible solve's result is stored in the 'result' attribute
(model.program.result) and its raw output in 'solver_out'.
```

### PR DESCRIPTION
**Pull request by bqpd**
Better Beam example and a couple of other things (mostly just automatic zero-lower-bound removal)

Closes #379

### CODE REVIEW

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
It's not testing the newest commit :(

**Comment by bqpd** [comment]
@whoburg this is ready for review

**Comment by whoburg** [comment]
This looks great! Final comment beyond the inlines: should the Beam model have a corresponding unit test?

**Comment by bqpd** [comment]
Like, add to t_examples?

**Comment by whoburg** [comment]
that could work, or maybe we should begin separating out the model package tests so that they can be run / not run by testing scripts (in case they get expensive)

**Comment by pgkirsch** [comment]
Is this ready to go by any chance? I'm itching to use units in SPs.

**Comment by whoburg** [comment]
Unless I missed an unresolved inline comment, I think this is ready to merge with the exception of adding a test. @bqpd, are you ready to merge this? If the only remaining issue is adding a test we can merge this and open a new issue for the test.

**Comment by bqpd** [comment]
There is a test already, in test_examples.

**Comment by bqpd** [comment]
Whoops, thought I'd responded to that comment. :p

**Comment by bqpd** [comment]
@pgkirsch gogogo

**Comment by pgkirsch** [comment]
Awesome thanks!

**Pull request merged**
