### PR TITLE
pylint challenge! 

### PR DESCRIPTION
**Pull request by galbramc**
Modify gpkit/tests/pylint.cfg to only create warnings and errors for things you care about. You can test with the command:

pylint --rcfile=gpkit/test/pylint.cfg $(find .  -name "*.py" -print) gpkit/

Alternatively you can rename gpkit/test/pylint.cfg to gpkit/../pylint or gpkit/../.pylintrc and
remove the need for the --rcfile flag.

### CODE REVIEW

**Comment by galbramc** [comment]
This was also a test to make sure jenkins did not build from a user that is not white listed. It worked as expected.

**Comment by galbramc** [comment]
Can one of the admins verify this patch?

**Comment by galbramc** [comment]
That last question was actually posted by jenkins (its using my user name a the moment and I need to fix that)

**Comment by bqpd** [comment]
Heh! This is great. Should we set it up to ignore the ctypesgen-generated files (which are a pylint disaster) and so on before merging?

**Comment by galbramc** [comment]
You should setup the config file so it tests what you think is appropriate to be tested. This most likely only means files that you are directly authoring. The file I committed is just the default pylint configuration file, I didn't make any changes to it.

**Comment by bqpd** [comment]
Sounds good.

**Comment by whoburg** [comment]
Guys, let's definitely talk together about what warnings/errors to keep vs. disable, before we make any changes.

**Comment by whoburg** [comment]
Continuing this in #216, so that we have access to make changes before merging.

**Pull request closed without merging**
