### PR TITLE
Fix MOSEK on macs

### LINKED ISSUE #416: El Capitan ruins everything
Causes 40 errors in unit tests (on master)

```
ImportError: Could not load MOSEK library: ImportError(OSError('dlopen(/Users/philippekirschen/.gpkit/expopt.so, 10): Library not loaded: @loader_path/libmosek64.7.0.dylib\n  Referenced from: /Users/philippekirschen/.gpkit/expopt.so\n  Reason: image not found',),)
```

Will post fix if/when I find it...

### PR DESCRIPTION
**Pull request by bqpd**
Closes #416 (confirmed on philippe's computer)

@galbramc, @whoburg, shall we try this with the el capitan test servers?

### CODE REVIEW

**Comment by whoburg** [comment]
I'm all for testing this on the el capitan test servers -- @galbramc if you could help with that we'd really appreciate it!

**Comment by whoburg** [comment]
This PR covers a bit more than just the Mac issues -- @bqpd change title to reflect that?

**Comment by bqpd** [comment]
Oops sorry my git got messed up...just a sec.

**Comment by bqpd** [comment]
Fixed!

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
Error in Windows MOSEK: `WindowsError: [Error 5] Access is denied: 'C:\\Users\\jenkins\\.gpkit\\expopt.so'`

**Comment by whoburg** [comment]
retest this please

**Comment by bqpd** [comment]
Working now, huh.

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
Asside from this
"""
Traceback (most recent call last):
  File "/Users/jenkins/workspace/gpkit_PullRequest/buildnode/macys_ElCap/optimizer/mosek/gpkit/tests/t_tools.py", line 16, in test_composite_objective
    obj = composite_objective(L+W, W**-1 * L**-3, sub={L: 1, W: 1})
  File "/Users/jenkins/workspace/gpkit_PullRequest/buildnode/macys_ElCap/optimizer/mosek/gpkit/tools.py", line 61, in composite_objective
    w_s = normalization[-1]*PosyArray(w_s)*objectives[-1]
TypeError: unsupported operand type(s) for *: 'int' and 'PosyArray'
"""

It looks like things are working on El Cap

**Comment by bqpd** [comment]
Those unsupported operand types on El Capitan only aren't seen on @pgkirsch's computer...they seem to pop up every so often?

**Comment by bqpd** [comment]
retest this please

**Comment by galbramc** [comment]
I don't have anaconda install on the mac. Could that have something to do with it?

**Comment by bqpd** [comment]
Maybe if the numpy versions are different?

**Comment by galbramc** [comment]
El Cap is using 1.8.0rc1 and Macericks is 1.9.2. I don't recall how I did the upgrade...

**Comment by galbramc** [comment]
retest this please

**Comment by galbramc** [comment]
I was able to upgrade numpy to 1.10.1, but now you get this error

```
Traceback (most recent call last):
  File "/Users/jenkins/workspace/gpkit_PullRequest/buildnode/macys_ElCap/optimizer/mosek/gpkit/tests/t_sub.py", line 122, in test_vector_sweep
    m.substitutions.update({y: ('sweep', [[2, 3], [5, 7, 11]])})
  File "/Users/jenkins/workspace/gpkit_PullRequest/buildnode/macys_ElCap/optimizer/mosek/gpkit/posyarray.py", line 46, in __hash__
    return getattr(self, "_hashvalue", np.ndarray.__hash__(self))
TypeError: 'NoneType' object is not callable
```

**Comment by bqpd** [comment]
progress! That's a much more reasonable error.

**Comment by galbramc** [comment]
Ok. I'll leave testing on El Cap turned on so you can get this fixed. Let me know when I should turn on El Cap for the testing of pushes directly to master

**Comment by whoburg** [comment]
retest this please

**Comment by bqpd** [comment]
I think the current issue is that the ElCap version of numpy no longer defines `ndarray.__hash__`

**Comment by whoburg** [comment]
@pgkirsch, what's your numpy version?

**Comment by pgkirsch** [comment]
anaconda: 1.9.2
system: 1.8.0rc1

**Comment by bqpd** [comment]
A difference between 1.10.1 and 1.9.2? :/

**Comment by whoburg** [comment]
@bqpd, do you have a clear vision forward on this?

**Comment by bqpd** [comment]
I'm going to try installing 1.10 on my computer and see if there's a good alternative. Otherwise we can use a different hashing function.

**Comment by galbramc** [comment]
I've downgraded numpy on the El Cap machine for now, and opened an issue for numpy 10.1. Let me know when I should upgrade numpy.

**Comment by galbramc** [comment]
retest this please

**Comment by bqpd** [comment]
Thanks @galbramc! (and thanks for opening the issue)

**Comment by bqpd** [comment]
@whoburg, this is ready to merge

**Comment by galbramc** [comment]
I removed the DYLIB stuff from the bash_profile on the mac. retest this please

**Comment by whoburg** [comment]
retest this please (just to be sure)

**Comment by whoburg** [comment]
thanks @galbramc !

**Pull request merged**
