### PR TITLE
Sub improvements

### PR DESCRIPTION
**Pull request by whoburg**
Started some attempts to clean up and document substitution. Others welcome to contribute as well.

Related:
 -  #267 
 -  #268 
 -  #279

### CODE REVIEW

**Comment by whoburg** [comment]
Would like to merge current changes into master, since they resolve #279 . @bqpd

**Comment by bqpd** [comment]
I'm not seeing where this fixes #279. It seems to assume that every varkey has a `.units`, but that's not true, is it?

**Comment by whoburg** [comment]
In fact, every `VarKey` does have a units! This is due to the line `self.units = self.descr.get("units", None)` in the VarKey `__init__`.

Note that I'm also proposing a simplified `VarKey` constructor, along with making units an `@property`, in #280.

By the way, the merge conflict on this is just in a docstring -- I will take the master version when merging (once @bqpd agrees this should be merged).

**Comment by whoburg** [comment]
Can we merge this? I want to make sure it doesn't get lost or become unmergable due to the GP refactor...

**Comment by bqpd** [comment]
Yes! Merge it on in.

**Pull request merged**
