### PR TITLE
Monomial equality refactor

### PR DESCRIPTION
**Pull request by whoburg**
Idea is that Monomial should deal with equality/inequality testing with numeric types...

Could alternatively implement comparison of `NomialData` with numeric types...

Currently fails unit tests, `Monomial.__ne__` is not implemented and falls back on an incorrect implementation by a parent.

### CODE REVIEW

**Comment by whoburg** [comment]
I'm back, I'll work on this

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
I squashed all commits into one. This is complete and ready for code review.

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
Looks good!

**Pull request merged**
