### PR TITLE
Define units from GPkit folder

### PR DESCRIPTION
**Pull request by bqpd**
See https://github.com/aeroa/gpkit-models/pull/24

### CODE REVIEW

**Comment by whoburg** [comment]
Now why is Jenkins unhappy... ?

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
retest this please, just to be sure. @galbramc, that was a strange testing failure -- temporary loss of internet connection?

**Comment by bqpd** [comment]
Worth noting that if we define currency by the year, we can easily define exchange rates...

**Comment by whoburg** [comment]
I'm ready to merge this, @bqpd please go ahead if you are too.

**Comment by bqpd** [comment]
:+1:

**Comment by bqpd** [comment]
@whoburg, See also the gpkit-models mod; should that be USD2012?

**Comment by whoburg** [comment]
Hmm good point -- would you basically hard-code the inflation rates by defining USD2012, USD2013, etc relative to some baseline, like USD1913?

I guess the other alternative is to expect users to continually update their code to use current labor rates, etc?

**Comment by bqpd** [comment]
Yerp.

**Comment by galbramc** [comment]
Looks like a loss of internet for some odd reason. No idea what happened there.

**Comment by whoburg** [comment]
I'm very open to adding the year-based dollar units, but of course we should also keep `USD` for models that don't want to worry about inflation.

**Comment by bqpd** [comment]
see https://github.com/aeroa/gpkit-models/pull/25

**Comment by bqpd** [comment]
see https://github.com/convexopt/gpkit/pull/494

**Pull request merged**
