### PR TITLE
Issue212

### PR DESCRIPTION
**Pull request by whoburg**
Proposed fix for issue #212

### CODE REVIEW

**Comment by bqpd** [comment]
This doesn't catch variables that are substituted but don't have values (such as sweeps). Should it?

**Comment by whoburg** [comment]
Yes, it should. My fault. Is there an easy way to do that, or is my plan of getting this info from a `VarKey` a dead end?

**Comment by bqpd** [comment]
Unfortunately it may be...whether something has recently been substituted or not is a more dynamic property than I feel comfortable putting into a VarKey.

**Comment by whoburg** [comment]
Ok, bailing on this strategy, and issue #212 remains open.

**Pull request closed without merging**
