### PR TITLE
tools library

### PR DESCRIPTION
**Pull request by whoburg**
started a `models/` directory to hold models that might be useful across applications.

### CODE REVIEW

**Comment by bqpd** [comment]
Looks good! Belongs in a `tools` library, along with what's in `user_scripts`?

**Comment by bqpd** [comment]
How would this be integrated with a models library?

**Comment by bqpd** [comment]
Decision: create 'tools.py' file. Models will go in a 'models' folder when the time comes.

**Comment by bqpd** [comment]
Good to merge when that's done.

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
retest this please

**Pull request merged**
