### PR TITLE
Added Embeddable Build Status

### PR DESCRIPTION
**Pull request by galbramc**
This should add an embedded build status to the main page (I think). Someone needs to push a commit directly to master to test the build.

### CODE REVIEW

**Comment by galbramc** [comment]
acdl-jenkins also needs admin access to the repo in order to setup testing of the master branch

**Comment by galbramc** [comment]
alternatively we can setup the hooks manually if you do not want to give acdl-jenkins admin access

**Comment by whoburg** [comment]
pushed c4ff92b5471399ecc8337b89512e90dac2a6988b directly to master. Should I expect to see a change in the icon at https://acdl.mit.edu/csi/buildStatus/icon?job=gpkit_Push?

**Comment by galbramc** [comment]
If you merge this branch into master, you should see the icon show up on the main gpkit page.

**Comment by galbramc** [comment]
The hooks are still not installed correctly to get the push directly to master to build

**Pull request merged**
