### PR TITLE
reintroduce error from #312; CI testing only; not to be merged

### PR DESCRIPTION
**Pull request by whoburg**

### CODE REVIEW

**Comment by galbramc** [comment]
As for the test again, I had it hard coded to test on the master to make sure I had things setup correctly

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
Worked perfectly

**Comment by galbramc** [comment]
It didn't. Things passed on the linux machine when it should have failed. I don't understand though how it passed...

**Comment by galbramc** [comment]
So I only get a failure on linux if I remove ~/.gpkit/expopt.so. So this is actually yet another reason why I need to serialize the testing since I now need to delete this file inbetween tests.

**Comment by galbramc** [comment]
ok try testing this one more time

**Comment by whoburg** [comment]
retest this please

**Comment by whoburg** [comment]
retest this please

**Comment by bqpd** [comment]
If you run mosek without having expopt.so, a failure will occur.

**Comment by whoburg** [comment]
That's the point -- we're trying to test with only cvxopt installed and fail for tests that request `solver="mosek"`

**Comment by bqpd** [comment]
We might be able to move expopt.so into the gpkit dir and remove ~/.gpkit entirely. We did that originally, then there was some bug such that adding ~/.gpkit was the easiest way to fix it, but now that gpkit_tmp doesn't need that folder it's worth re-examining.

**Comment by bqpd** [comment]
@whoburg ... is the desired behaviour failure, then?

**Comment by whoburg** [comment]
that would be excellent! 

the desired behavior for this PR is for cvxopt-only testing to fail on both Reynolds and Macys.

**Comment by whoburg** [comment]
retest this please

**Comment by bqpd** [comment]
The easiest fix for this would be for a cvxopt-only install to refuse to even try to solve with MOSEK.

**Comment by whoburg** [comment]
This is just a temporary PR to get the CI setup correctly. Once it's catching the error introduced by this PR we will delete this PR unmerged.

**Comment by galbramc** [comment]
The testing properly catches this error. We can remove this PR now.

**Comment by whoburg** [comment]
hallelujah

**Pull request closed without merging**
