### PR TITLE
PosyArray improvements

### PR DESCRIPTION
**Pull request by whoburg**
* implement new convenience methods useful for finite-differencing `PosyArray`s

Example usage:
```python
from gpkit import VectorVariable
x = VectorVariable(10, 'x', 'm')
dx = VectorVariable(10, 'dx', 'm')
constraint = (x >= x.left + dx/2. + dx.left/2.)
```

### CODE REVIEW

**Comment by bqpd** [comment]
The above also imposes the constraint `x[0] >= dx[0]/2`, is that intended?

**Comment by bqpd** [comment]
(also, do you think this should be an @property so that you can do `x.left`?)

**Comment by whoburg** [comment]
Yes, the idea on imposing `x[0] >= dx[0]/2` is that the `x`'s are the center of some computational bins, and the `dx`s are the bin widths. Therefore, the first x should be at least half a bin width from zero.

I went back and forth on @property, and I don't have a strong opinion. I'll change it to a property, sounds user-friendly for modelers.

**Comment by whoburg** [comment]
The names might need work. On the plus side, they're easy and short when this is the behavior you want :/

**Comment by bqpd** [comment]
Sounds good to me! The names `left` and `right` aren't super clear to me (though, no strong opinion).

Alternatives:
  - `leftshift`/`rightshift`
  - `lshift`
  - `bumpleft`

**Comment by bqpd** [comment]
`left` and `right` seem fine, but for whatever reason my first guess was that `left` would leave a 0 on the left

**Comment by whoburg** [comment]
`left` does indeed leave a 0 in the leftmost position.

My concern about `bumpleft` (and the related alternatives) is that they sound like we're bumping/shifting the entries in the PosyArray. In contrast, here we're bumping the indices. "shift your view over one and sample there". I claim this is the most intuitive behavior if you're thinking about finite differences, i.e.

`dx = x.right - x.left`

But there's definitely potential confusion here

**Comment by bqpd** [comment]
So it does! I know I got it wrong at first, so guess I've already internalized it. :)

I'd say this looks good to merge! Might be good to get @cjk12's opinion on syntax, since he's written these constraints before?

**Pull request merged**
