### PR TITLE
test #274

### PR DESCRIPTION
**Pull request by bqpd**
test #274

### CODE REVIEW

**Comment by bqpd** [comment]
It works on the mac system, but none of the others? And it works on @pgkirsch's and my computers. Weird...

**Comment by galbramc** [comment]
test this please

**Comment by whoburg** [comment]
Those `ValueError`s on jenkins match the errors I'm seeing on my system.

**Comment by bqpd** [comment]
Yerp. This is the first non-OS-specific bug I haven't been able to reproduce on my machine...which makes me suspect it might be a package version bug?

**Comment by whoburg** [comment]
```python
In [1]: import numpy

In [2]: numpy.__version__
Out[2]: '1.9.2'
```

**Comment by whoburg** [comment]
which reminds me -- 

```python
In [4]: import gpkit

In [5]: gpkit.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-4300fb7eb2bd> in <module>()
----> 1 gpkit.__version__

AttributeError: 'module' object has no attribute '__version__'
```

**Comment by bqpd** [comment]
I've got the same numpy version.

Ack, we have to add another place to change the version number?

**Comment by whoburg** [comment]
Not  big deal, that's feature creep as far as this issue is concerned.

**Comment by bqpd** [comment]
Yup, put it in #332

**Comment by galbramc** [comment]
On the linux machine

>>> numpy.__version__
'1.8.2'

on OS X

>>> numpy.__version__
'1.9.2'

**Comment by whoburg** [comment]
@bqpd does this work for you on all operating systems you have access to?

**Comment by whoburg** [comment]
bingo, it just occurred to me what might be going on. The optimal objective value for this is 0.0. I wonder if we're dealing with floating point precision making that objective slightly negative.

Indeed, if I add 0.1 to `J`, I get the correct `x = y = 1`, and the correct cost of 0.1.

I think the monomial approximation of a signomial about a point where the signomial takes on a negative value is not defined... ? But I need to think that through for more than the 15 seconds I just allotted to it...

**Comment by whoburg** [comment]
That still leaves the issue of why this:

```python
import gpkit
from gpkit import Model, Variable

x = Variable('x')
y = Variable('y')
z = Variable('z')

with gpkit.EnableSignomials():
    J = 1*((x - 1)**2 + (y - 1)**2) + (x*y - 1)**2 + 0.1
    sp = Model(J, [])
    sol = sp.localsolve()

print sol.table()

# output

Beginning signomial solve.
Solving took 3 GP solves and 0.12 seconds.

Cost
----
 0.8643

Free Variables
--------------
x : 0.9059
y : 0.9059

Sensitivities
-------------


Cost
----
 0.8643

Free Variables
--------------
x : 0.9059
y : 0.9059

Sensitivities
-------------
```

gives a different answer than the almost equivalent

```python
import gpkit
from gpkit import Model, Variable

x = Variable('x')
y = Variable('y')
z = Variable('z')

with gpkit.EnableSignomials():
    J = 1*((x - 1)**2 + (y - 1)**2) + (x*y - 1)**2 + 0.1
    sp = Model(z, [z >= J])
    sol = sp.localsolve()

print sol.table()

# output

Beginning signomial solve.
Solving took 7 GP solves and 0.145 seconds.

Cost
----
 0.1

Free Variables
--------------
x : 1
y : 1
z : 0.1

Sensitivities
-------------


Cost
----
 0.1

Free Variables
--------------
x : 1
y : 1
z : 0.1

Sensitivities
-------------
```

**Comment by whoburg** [comment]
and this discussion should really be moved back to #274

**Comment by bqpd** [comment]
retest this please

**Comment by galbramc** [comment]
@bqpd did you push two commits at once?

**Comment by bqpd** [comment]
Yup.

**Comment by bqpd** [comment]
retest this please

**Comment by bqpd** [comment]
retest this please

**Comment by galbramc** [comment]
It appears that jenkins tried to test each one of them, rather than just the most recent one... I didn't expect that... This is also the reason why the test are failing. You should be able to push multuiple commits and it should only test the most recent one. I'll look to see if there is a setting related to this, but we might need the webhooks to get it to only test the most recent commit.

**Comment by bqpd** [comment]
@whoburg, this is passing now.

**Comment by galbramc** [comment]
test this please (I made some changes to jenkins)

**Comment by bqpd** [comment]
Looks like it didn't install cvxopt

**Comment by galbramc** [comment]
I tried setting up a virtualenv with cvxopt installed, and then load it from the script. Not sure why it's not working. I can import cvxopt in the virtualenv from the command line

**Comment by galbramc** [comment]
test this please (I'm giving up on the virtualenv for now and working on it later)

**Comment by whoburg** [comment]
Sorry guys, I'm not convinced on the `1e-5`. As I understand it, this considers any SP with a cost less than 1e-5 converged?

First, I would have expected a cutoff of `> 0` to work. I still think the fundamental issue has to do with making monomial approximations of signomials with value ` <= 0`. I see no reason why a nonzero cutoff should be needed.

Changing the cutoff to 0 doesn't pass the unit test for this issue, though. I think that's because the cost cutoff only addresses the objective, but we need to address the constraints too. We'll need to think carefully about how to do that -- possibly in a separate issue.

For now, I've proposed a patch (will push it in a moment) that simply adds a small constant to `J` for this example.

I think we should leave handling signomials that evaluate to `<= 0` for either 0.5 or for 0.3.1.

**Comment by whoburg** [comment]
this PR was originally just for testing. Is anyone's intent that it ever gets merged? If not let's close it.

**Comment by bqpd** [comment]
re: not handling Signomials <= 0, sounds good

**Pull request closed without merging**
